services:
  - type: web
    name: gainsight-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Generalize.py --server.port $PORT --server.address 0.0.0.0
    plan: free
